Repository yee2542/FluentSearch-BFF, pull requests merged in 2021-01, with the labels that each got.

#17 CD & Docker integration
  .dockerignore
  .gitattributes
  .github/workflows/dockerhub.yml
  .gitignore
  Dockerfile
  README.md
  db/cfg/.gitkeep
  db/shard-0/.gitkeep
  docker-compose.dev.yml
  src/config/config.enum.ts
  src/config/config.interface.ts
  src/config/config.providers.ts
  src/main.ts
  tsconfig.build.json
Labels: in progress

#19 Enable esModuleInterop
  .github/workflows/ci.yml
  test/app-graphql.e2e-spec.ts
  test/app.e2e-spec.ts
  tsconfig.json
Labels: ready for review

#4 [DF-35] User register with validation data
  docker-compose.dev.yml
  generate-gql.ts
  package.json
  schema.gql
  src/app.module.ts
  src/common/exception/duplicated-email.exception.ts
  src/common/exception/user-not-exists.exception.ts
  src/common/filters/user-error.filter.ts
  src/config/config.enum.ts
  src/config/config.interface.ts
  src/config/config.providers.ts
  src/database/constants/database.constant.ts
  src/database/database.module.ts
  src/database/database.provider.ts
  src/user/constants/user.collection.constant.ts
  src/user/constants/user.provider.constant.ts
  src/user/dtos/args/skip-limit.args.ts
  src/user/dtos/inputs/user-register.input.ts
  src/user/dtos/inputs/user-update.input.ts
  src/user/interfaces/user-token.ts
  src/user/interfaces/user.ts
  src/user/models/user-query-returns.model.ts
  src/user/models/user-token.model.ts
  src/user/models/user.model.ts
  src/user/schemas/enums/oauth-provider.enum.ts
  src/user/schemas/enums/user-package.enum.ts
  src/user/schemas/enums/user-role.enum.ts
  src/user/schemas/enums/user.zone.enum.ts
  src/user/schemas/user-token.schema.ts
  src/user/schemas/user.schema.ts
  src/user/user.module.ts
  src/user/user.providers.ts
  src/user/user.resolver.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  test/app-graphql.e2e-spec.ts
  test/app.e2e-spec.ts
  test/mock/mongodb.mock.factory.ts
  test/user-resolver.e2e-spec.ts
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: dependency changed, in progress
